let currentJSON = "1789";
let width = $(window).width() * 0.7;
let height = $(window).height() * 0.7;
let defaultcolor = "white";
let centered;
let svg, g, currentState;
let outOfSVG;
let sideBarHidden = true;
let animationLength = 300;
let clickedDOM;
let hoveredOld;
let zoomedIn;
let possibleYears = [];
let id = parseInt(currentJSON) - 1;